kind: pipeline
type: docker
name: frontend

steps:
  - name: Checkout to the repository
    image: alpine/git
    commands:
      - git clone --depth=1 "${DRONE_REPO_LINK}"
      - .cicd/scripts/must_continue_pipeline.sh web

  - name: Install Dependencies
    image: node:23-alpine
    depends_on:
      - Checkout to the repository
    commands:
      - npm --prefix=web install

  - name: Running Tests
    image: node:23-alpine
    depends_on:
      - Install Dependencies
    commands:
      - npm --prefix=web run test

  - name: Building
    image: plugins/docker
    privileged: true
    depends_on:
      - Running Tests
    environment:
      ENV_CONTENT:
        from_secret: ENV_CONTENT
    settings:
      registry: ghcr.io
      repo: ghcr.io/jspereiramoura/habit-tracker/web
      dockerfile: web/.docker/Dockerfile
      context: web
      build_args_from_env:
        - ENV_CONTENT
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_TOKEN
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:7}
    
  - name: Deploy
    image: curlimages/curl
    depends_on:
      - Building
    environment:
      FRONTEND_WEBHOOK_URL:
        from_secret: FRONTEND_WEBHOOK_URL
    commands:
      - >
        curl -X GET "$FRONTEND_WEBHOOK_URL"

  - name: Send Telegram Notification
    image: appleboy/drone-telegram
    when:
      status:
        - success
        - failure
    depends_on:
      - Deploy
    settings:
      token:
        from_secret: TELEGRAM_TOKEN
      to:
        from_secret: TELEGRAM_ID
      message_file: .cicd/message_file.tpl
      template_vars:
        env: "production"
        app: "Owl Habit Tracker - Frontend"
        url: https://apps.habits.jspereiramoura.dev.br

---

kind: pipeline
type: docker
name: api

steps:
  - name: Checkout to the repository
    image: alpine/git
    commands:
      - git clone --depth=1 "${DRONE_REPO_LINK}"
      - .cicd/scripts/must_continue_pipeline.sh api

  - name: Install Dependencies
    image: node:23-alpine
    depends_on:
      - Checkout to the repository
    commands:
      - npm --prefix=api install

  - name: Running Tests
    image: node:23-alpine
    depends_on:
      - Install Dependencies
    commands:
      - npm --prefix=api run test

  - name: Building
    image: plugins/docker
    privileged: true
    depends_on:
      - Running Tests
    settings:
      registry: ghcr.io
      repo: ghcr.io/jspereiramoura/habit-tracker/api
      dockerfile: api/.docker/Dockerfile
      context: api
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_TOKEN
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:7}
    
  - name: Deploy
    image: curlimages/curl
    depends_on:
      - Building
    environment:
      BACKEND_WEBHOOK_URL:
        from_secret: BACKEND_WEBHOOK_URL
    commands:
      - >
        curl -X GET "$BACKEND_WEBHOOK_URL"

  - name: Send Telegram Notification
    image: appleboy/drone-telegram
    depends_on:
      - Deploy
    when:
      status:
        - success
        - failure
    settings:
      token:
        from_secret: TELEGRAM_TOKEN
      to:
        from_secret: TELEGRAM_ID
      message_file: .cicd/message_file.tpl
      template_vars:
        env: "production"
        app: "Owl Habit Tracker - API"
        url: https://api.habits.jspereiramoura.dev.br/swagger

trigger:
  branch:
    - main
