version: "3.8"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file: .env
    networks:
      - habit_tracker_network
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS

networks:
  habit_tracker_network:
    driver: bridge