services:
  api: 
    build: 
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: habit-tracker-api
    ports:
      - 3000:3000
    env_file: .env
    networks:
      - habit_tracker_network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file: .env
    container_name: habit-tracker-db
    networks:
      - habit_tracker_network
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  habit_tracker_network:
    driver: bridge